#!/usr/bin/env bash
#-*-coding:utf-8-*-
# ******************************************************
# Author       : kaleo
# Last modified: 2017-03-25 19:39
# Email        : kaleo1990@hotmail.com
# Filename     : opendb
# Description  : 
# ******************************************************
./proxychains4 /home/kaleo/dbeaver/dbeaver
